FROM oven/bun:1.3.4-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN bun install

COPY . .
RUN bun run build


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/host/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
